export const playgroundGroups = [
  { id: 'feedback', label: '反馈' },
  { id: 'display', label: '展示' },
  { id: 'layout', label: '布局' },
  { id: 'input', label: '录入' },
  { id: 'data', label: '数据' },
  { id: 'navigation', label: '导航' },
] as const

export type PlaygroundGroupId = (typeof playgroundGroups)[number]['id']

export interface PlaygroundNavItem {
  id: string
  label: string
  name?: string
  group: PlaygroundGroupId
  description: string
  scenarios: string[]
}

const componentNameOverrides: Record<string, string> = {
  qrcode: 'QR Code',
}

function formatComponentName(id: string) {
  return (
    componentNameOverrides[id] ??
    id
      .split('-')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ')
  )
}

export const playgroundNavItems: PlaygroundNavItem[] = [
  {
    id: 'affix',
    label: '固钉',
    group: 'navigation',
    description: '用于把操作入口或导航节点固定在滚动容器的指定位置。',
    scenarios: ['长表单提交栏', '内容目录', '批量操作入口'],
  },
  {
    id: 'alert',
    label: '提示',
    group: 'feedback',
    description: '用于展示页面级提示、状态说明和可关闭的轻量反馈。',
    scenarios: ['系统公告', '校验提醒', '流程状态说明'],
  },
  {
    id: 'anchor',
    label: '锚点',
    group: 'navigation',
    description: '用于在长内容页面中快速定位标题和业务区块。',
    scenarios: ['文档目录', '配置页导航', '报告章节跳转'],
  },
  {
    id: 'message',
    label: '消息',
    group: 'feedback',
    description: '用于展示即时操作结果，不打断用户当前任务。',
    scenarios: ['保存成功', '复制完成', '轻量错误提示'],
  },
  {
    id: 'notification',
    label: '通知',
    group: 'feedback',
    description: '用于承载比消息更完整的异步提醒和任务状态。',
    scenarios: ['构建提醒', '审批到达', '后台任务完成'],
  },
  {
    id: 'back-top',
    label: '回到顶部',
    group: 'navigation',
    description: '用于长页面滚动后的快速返回，降低重复滚动成本。',
    scenarios: ['列表页', '文档页', '运营配置页'],
  },
  {
    id: 'dialog',
    label: '对话框',
    group: 'feedback',
    description: '用于需要用户确认、填写或聚焦处理的阻塞式任务。',
    scenarios: ['删除确认', '快捷编辑', '二次确认'],
  },
  {
    id: 'drawer',
    label: '抽屉',
    group: 'feedback',
    description: '用于在不离开当前页面的情况下承载详情、筛选和编辑任务。',
    scenarios: ['订单详情', '高级筛选', '侧边编辑'],
  },
  {
    id: 'command-palette',
    label: '命令面板',
    group: 'navigation',
    description: '用于集中执行命令、搜索资源和快速切换工作上下文。',
    scenarios: ['全局搜索', '快捷命令', '页面跳转'],
  },
  {
    id: 'text',
    label: '文本',
    group: 'display',
    description: '用于统一正文、标题、辅助说明和状态文本的视觉层级。',
    scenarios: ['详情说明', '列表字段', '辅助文案'],
  },
  {
    id: 'link',
    label: '链接',
    group: 'navigation',
    description: '用于页面跳转、外链访问和文本内操作入口。',
    scenarios: ['详情跳转', '下载入口', '帮助链接'],
  },
  {
    id: 'icon',
    label: '图标',
    group: 'display',
    description: '用于承载轻量视觉语义，辅助按钮、状态和信息层级表达。',
    scenarios: ['工具按钮', '状态提示', '导航标识'],
  },
  {
    id: 'avatar',
    label: '头像',
    group: 'display',
    description: '用于展示用户、组织或对象身份，并支持兜底内容。',
    scenarios: ['成员列表', '评论区', '协作卡片'],
  },
  {
    id: 'image',
    label: '图片',
    group: 'display',
    description: '用于展示业务图片、封面资源和可预览素材。',
    scenarios: ['商品图', '内容封面', '附件预览'],
  },
  {
    id: 'badge',
    label: '角标',
    group: 'display',
    description: '用于表达数量、状态和新内容提醒。',
    scenarios: ['未读数量', '任务状态', '新增提示'],
  },
  {
    id: 'breadcrumb',
    label: '面包屑',
    group: 'navigation',
    description: '用于展示页面层级路径，帮助用户回到上级位置。',
    scenarios: ['后台详情页', '文件目录', '配置层级'],
  },
  {
    id: 'tag',
    label: '标签',
    group: 'display',
    description: '用于承载状态、分类、筛选项和可关闭的轻量信息块。',
    scenarios: ['订单状态', '用户分组', '筛选条件'],
  },
  {
    id: 'tag-input',
    label: '标签输入',
    group: 'input',
    description: '用于录入多个短文本标签，并支持快速创建、删除和限制数量。',
    scenarios: ['客户画像', '任务标记', '内容关键词'],
  },
  {
    id: 'tooltip',
    label: '文字提示',
    group: 'feedback',
    description: '用于补充说明图标、字段和被截断的信息。',
    scenarios: ['图标说明', '字段解释', '省略内容预览'],
  },
  {
    id: 'popconfirm',
    label: '气泡确认框',
    group: 'feedback',
    description: '用于就地完成轻量二次确认，避免完整对话框打断流程。',
    scenarios: ['删除确认', '撤销操作', '状态切换确认'],
  },
  {
    id: 'popover',
    label: '气泡卡片',
    group: 'display',
    description: '用于承载就近的补充信息、快捷操作和摘要内容。',
    scenarios: ['用户资料', '指标解释', '快捷操作'],
  },
  {
    id: 'tour',
    label: '漫游式引导',
    group: 'feedback',
    description: '用于把新功能、关键路径和复杂操作分步引导给用户。',
    scenarios: ['新手引导', '功能发布', '流程培训'],
  },
  {
    id: 'dropdown',
    label: '下拉菜单',
    group: 'navigation',
    description: '用于收纳一组上下文操作或可选命令。',
    scenarios: ['更多操作', '账户菜单', '批量命令'],
  },
  {
    id: 'card',
    label: '卡片',
    group: 'display',
    description: '用于把相关信息组织成可扫描、可操作的独立内容块。',
    scenarios: ['数据概览', '资源列表', '工作台模块'],
  },
  {
    id: 'collapse',
    label: '折叠面板',
    group: 'display',
    description: '用于把同类内容分组收纳，减少页面初始信息密度。',
    scenarios: ['高级配置', '问题列表', '分组详情'],
  },
  {
    id: 'empty',
    label: '空状态',
    group: 'feedback',
    description: '用于解释无数据原因，并提供下一步操作。',
    scenarios: ['搜索无结果', '列表为空', '权限范围为空'],
  },
  {
    id: 'result',
    label: '结果',
    group: 'feedback',
    description: '用于展示流程完成后的明确状态和后续动作。',
    scenarios: ['提交成功', '支付失败', '审批完成'],
  },
  {
    id: 'skeleton',
    label: '骨架屏',
    group: 'feedback',
    description: '用于数据加载期间维持布局稳定并降低等待感。',
    scenarios: ['列表加载', '详情加载', '卡片加载'],
  },
  {
    id: 'loading',
    label: '加载',
    group: 'feedback',
    description: '用于表达局部或全局任务正在处理中。',
    scenarios: ['按钮提交', '表格刷新', '页面初始化'],
  },
  {
    id: 'watermark',
    label: '水印',
    group: 'display',
    description: '用于在敏感内容区域叠加身份或环境标记。',
    scenarios: ['内部报表', '预览页面', '截图溯源'],
  },
  {
    id: 'resizable',
    label: '可调整尺寸',
    group: 'layout',
    description: '用于让用户按任务需要调整面板、区域或内容块尺寸。',
    scenarios: ['看板列宽', '编辑器侧栏', '报表面板'],
  },
  {
    id: 'splitter',
    label: '分割面板',
    group: 'layout',
    description: '用于构建可拖拽调整的多区域工作界面。',
    scenarios: ['编辑器布局', '左右详情', '监控面板'],
  },
  {
    id: 'divider',
    label: '分割线',
    group: 'layout',
    description: '用于分隔内容层级、操作区域和语义段落。',
    scenarios: ['详情分组', '菜单分隔', '表单区块'],
  },
  {
    id: 'space',
    label: '间距',
    group: 'layout',
    description: '用于稳定排列按钮、标签和小型组件组合。',
    scenarios: ['操作按钮组', '标签列表', '工具栏'],
  },
  {
    id: 'grid',
    label: '网格',
    group: 'layout',
    description: '用于构建响应式列布局和有规律的信息陈列。',
    scenarios: ['指标栅格', '商品列表', '表单布局'],
  },
  {
    id: 'rate',
    label: '评分',
    group: 'input',
    description: '用于表达满意度、质量评分和偏好强度。',
    scenarios: ['服务评价', '内容评分', '体验反馈'],
  },
  {
    id: 'slider',
    label: '滑块',
    group: 'input',
    description: '用于在连续数值范围内快速选择或调整参数。',
    scenarios: ['预算范围', '音量控制', '权重配置'],
  },
  {
    id: 'menu',
    label: '菜单',
    group: 'navigation',
    description: '用于组织应用级导航、侧栏入口和分组命令。',
    scenarios: ['后台导航', '设置中心', '权限菜单'],
  },
  {
    id: 'input',
    label: '输入框',
    group: 'input',
    description: '用于录入文本、搜索关键字和结构化字段。',
    scenarios: ['关键词搜索', '资料编辑', '备注填写'],
  },
  {
    id: 'input-number',
    label: '数字输入框',
    group: 'input',
    description: '用于录入可增减、可限制范围的数值。',
    scenarios: ['库存数量', '预算金额', '权重比例'],
  },
  {
    id: 'layout',
    label: '布局',
    group: 'layout',
    description: '用于搭建页面头部、侧栏、内容和页脚结构。',
    scenarios: ['管理后台', '应用框架', '工作台页面'],
  },
  {
    id: 'sidebar',
    label: '侧栏',
    group: 'layout',
    description: '用于承载页面中长期存在的导航、筛选和辅助信息面板。',
    scenarios: ['常驻导航', '筛选面板', '辅助详情'],
  },
  {
    id: 'select',
    label: '选择器',
    group: 'input',
    description: '用于从候选项中选择单个或多个结构化值。',
    scenarios: ['负责人选择', '状态筛选', '分类设置'],
  },
  {
    id: 'cascader',
    label: '级联选择',
    group: 'input',
    description: '用于选择具有层级关系的数据。',
    scenarios: ['地区选择', '组织架构', '商品类目'],
  },
  {
    id: 'autocomplete',
    label: '自动完成',
    group: 'input',
    description: '用于在输入过程中提供候选建议并减少录入成本。',
    scenarios: ['客户搜索', '地址输入', '标签补全'],
  },
  {
    id: 'mention',
    label: '提及',
    group: 'input',
    description: '用于在文本输入中快速引用用户、话题或资源。',
    scenarios: ['评论协作', '任务备注', '群组消息'],
  },
  {
    id: 'tabs',
    label: '标签页',
    group: 'navigation',
    description: '用于在同层级内容之间切换，保持页面上下文稳定。',
    scenarios: ['详情分栏', '配置分组', '数据视图切换'],
  },
  {
    id: 'segmented',
    label: '分段控制器',
    group: 'input',
    description: '用于在少量互斥选项中快速切换。',
    scenarios: ['时间维度', '视图模式', '状态范围'],
  },
  {
    id: 'color-picker',
    label: '颜色选择器',
    group: 'input',
    description: '用于选择品牌色、标记色和可视化颜色配置。',
    scenarios: ['主题配置', '标签颜色', '图表配色'],
  },
  {
    id: 'calendar',
    label: '日历',
    group: 'data',
    description: '用于展示日期网格、事件排期和日程状态。',
    scenarios: ['排班计划', '内容日历', '活动排期'],
  },
  {
    id: 'date-picker',
    label: '日期选择器',
    group: 'input',
    description: '用于选择单个日期并写入表单或筛选条件。',
    scenarios: ['截止日期', '生日录入', '统计日期'],
  },
  {
    id: 'date-range-picker',
    label: '日期范围选择器',
    group: 'input',
    description: '用于选择连续日期区间，常见于查询和排期。',
    scenarios: ['报表周期', '活动时间', '订单筛选'],
  },
  {
    id: 'time-picker',
    label: '时间选择器',
    group: 'input',
    description: '用于选择具体时间点并处理格式化展示。',
    scenarios: ['提醒时间', '预约时间', '任务触发时间'],
  },
  {
    id: 'time-range-picker',
    label: '时间范围选择器',
    group: 'input',
    description: '用于选择一天内的起止时间。',
    scenarios: ['营业时段', '会议时间', '排班区间'],
  },
  {
    id: 'table',
    label: '表格',
    group: 'data',
    description: '用于展示结构化数据，并支持列配置、状态和空数据表达。',
    scenarios: ['成员列表', '订单管理', '指标明细'],
  },
  {
    id: 'list',
    label: '列表',
    group: 'data',
    description: '用于展示一组同构信息，适合中等密度的数据浏览。',
    scenarios: ['消息列表', '任务清单', '资源列表'],
  },
  {
    id: 'virtual-list',
    label: '虚拟列表',
    group: 'data',
    description: '用于大量数据的高性能滚动展示。',
    scenarios: ['日志列表', '成员名录', '消息历史'],
  },
  {
    id: 'tree',
    label: '树',
    group: 'data',
    description: '用于展示和操作层级数据。',
    scenarios: ['组织架构', '目录树', '权限节点'],
  },
  {
    id: 'transfer',
    label: '穿梭框',
    group: 'data',
    description: '用于在两个集合之间移动、筛选和确认候选项。',
    scenarios: ['分配成员', '授权资源', '配置字段'],
  },
  {
    id: 'descriptions',
    label: '描述列表',
    group: 'data',
    description: '用于展示只读详情字段和分组信息。',
    scenarios: ['用户资料', '订单详情', '设备信息'],
  },
  {
    id: 'pagination',
    label: '分页',
    group: 'navigation',
    description: '用于控制分批数据浏览和页码跳转。',
    scenarios: ['表格分页', '搜索结果', '列表翻页'],
  },
  {
    id: 'progress',
    label: '进度条',
    group: 'feedback',
    description: '用于表达任务完成比例、阶段进度和容量占比。',
    scenarios: ['上传进度', '任务完成率', '配额使用'],
  },
  {
    id: 'qrcode',
    label: '二维码',
    group: 'display',
    description: '用于生成可扫码访问、绑定或分享的信息。',
    scenarios: ['登录确认', '移动端预览', '活动分享'],
  },
  {
    id: 'statistic',
    label: '统计数值',
    group: 'data',
    description: '用于突出展示关键指标、趋势和实时数值。',
    scenarios: ['经营看板', '任务统计', '实时监控'],
  },
  {
    id: 'steps',
    label: '步骤条',
    group: 'navigation',
    description: '用于展示多步骤流程的当前位置和完成状态。',
    scenarios: ['审批流程', '发布向导', '支付步骤'],
  },
  {
    id: 'timeline',
    label: '时间轴',
    group: 'data',
    description: '用于按时间顺序展示事件、日志和处理记录。',
    scenarios: ['操作日志', '审批记录', '版本历史'],
  },
  {
    id: 'upload',
    label: '上传',
    group: 'input',
    description: '用于选择、校验和展示待上传文件。',
    scenarios: ['附件上传', '头像更新', '资料导入'],
  },
  {
    id: 'checkbox',
    label: '复选框',
    group: 'input',
    description: '用于多选、确认项和布尔状态录入。',
    scenarios: ['批量选择', '权限配置', '协议确认'],
  },
  {
    id: 'radio',
    label: '单选框',
    group: 'input',
    description: '用于在多个互斥选项中选择一个明确值。',
    scenarios: ['支付方式', '优先级', '配置模式'],
  },
  {
    id: 'switch',
    label: '开关',
    group: 'input',
    description: '用于即时切换启用、关闭或发布状态。',
    scenarios: ['功能开关', '通知订阅', '上下架状态'],
  },
  {
    id: 'form',
    label: '表单',
    group: 'input',
    description: '用于组织字段、校验提示和提交操作。',
    scenarios: ['资料维护', '配置提交', '创建工单'],
  },
  {
    id: 'button',
    label: '按钮',
    group: 'input',
    description: '用于触发页面操作、提交任务和表达操作层级。',
    scenarios: ['主操作', '次要操作', '危险操作'],
  },
]

playgroundNavItems.forEach((item) => {
  item.name ??= formatComponentName(item.id)
})
